version: "3"
services:
  firefox:
      image: selenoid/firefox
  chrome:
      image: selenoid/chrome
      depends_on:
        - firefox
  video:
      image: selenoid/video-recorder
      depends_on:
        - chrome
  selenoid:
      network_mode: bridge
      image: aerokube/selenoid:latest-release
      container_name: "selenoid"
      depends_on:
        - video
      volumes:
        - "$PWD/selenoid:/etc/selenoid"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/etc/selenoid/video:/opt/selenoid/video"
        - "/etc/selenoid/logs:/opt/selenoid/logs"
      environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
        - OVERRIDE_LOGS_OUTPUT_DIR=$PWD/selenoid/logs
      command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
      ports:
        - "4444:4444"
  selenoid-ui:
      image: aerokube/selenoid-ui
      depends_on:
        - selenoid
      container_name: "selenoid-ui"
      network_mode: bridge
      links:
        - selenoid
      ports:
        - "8080:8080"
      command: ["--selenoid-uri","http://selenoid:4444"]
  search-module:
      image: sromankov/selenium-docker
      depends_on:
        - selenoid
        - selenoid-ui
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=search_module.xml
      network_mode: bridge
      volumes:
        - ./search-result:/usr/share/test/test-output
