version: "3"
services:
  firefox:
      image: selenoid/vnc_firefox:76.0
      shm_size: '1gb'
  chrome:
      image: selenoid/vnc_chrome:83.0
      depends_on:
        - firefox
  video:
      image: selenoid/video-recorder:6.1
      depends_on:
        - chrome
  selenoid:
      network_mode: bridge
      image: aerokube/selenoid:1.10.0
      container_name: "selenoid"
      depends_on:
        - video
      volumes:
        - "$PWD/selenoid:/etc/selenoid"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "$PWD/selenoid/video:/opt/selenoid/video"
        - "/etc/selenoid/logs:/opt/selenoid/logs"
      environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
      command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
      ports:
        - "4444:4444"
  selenoid-ui:
      image: aerokube/selenoid-ui:1.10.0
      depends_on:
        - selenoid
      container_name: "selenoid-ui"
      network_mode: bridge
      links:
        - selenoid
      ports:
        - "8080:8080"
      command: ["--selenoid-uri","http://selenoid:4444"]
  search-module:
      image: sromankov/selenium-docker
      container_name: "module"
      depends_on:
        - selenoid
        - selenoid-ui
      environment:
        - BROWSER=firefox
        - HUB_HOST=selenoid
        - MODULE=search_module.xml
      network_mode: bridge
      links:
        - selenoid
        - selenoid-ui
      volumes:
        - ./search-result:/usr/share/test/test-output
  search-module-chrome:
    image: sromankov/selenium-docker
    container_name: "module_chrome"
    depends_on:
      - selenoid
      - selenoid-ui
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenoid
      - MODULE=search_module.xml
    network_mode: bridge
    links:
      - selenoid
      - selenoid-ui
    volumes:
      - ./search-result-chrome:/usr/share/test/test-output
  books-module:
      image: sromankov/selenium-docker
      container_name: "bmodule"
      depends_on:
        - selenoid
        - selenoid-ui
      environment:
        - BROWSER=chrome
        - HUB_HOST=selenoid
        - MODULE=testng.xml
      network_mode: bridge
      links:
        - selenoid
        - selenoid-ui
      volumes:
        - ./book-result:/usr/share/test/test-output
  books-moduleff:
    image: sromankov/selenium-docker
    container_name: "bmoduleff"
    depends_on:
      - selenoid
      - selenoid-ui
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenoid
      - MODULE=testng.xml
    network_mode: bridge
    links:
      - selenoid
      - selenoid-ui
    volumes:
      - ./book-resultff:/usr/share/test/test-output
